# Gets included from etc/Makefile.testgen

runtests: ._.$(suite).$(coverage).rpt

$(eval $(call mvn-test-compile,$(suite)))
$(eval $(call do-report,$(suite),$(coverage)))

._.$(suite).testrun: ._.$(suite).test.compiled ._.$(suite).tests.created | $(root)/build
	$(MAKE) ._.$(suite).testclasses
	@touch $@

