suite=randoop
include $(root)/etc/Makefile.incl

.$(suite).tests.created: project.jar .classes
	echo $(suite) --------------------
	rm -rf src/test
	env project=$(project) timeout=$(timeout) $(root)/bin/randoop-gen.sh -x
	$(mvn) clean && $(mvn) test-compile
	touch $@


